version: '3'
services:
  autonomous-brokering-engine:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 3000:3000
    environment:
      CHAIN: ${NODE}
      MNEMONIC: ${MNEMONIC}
      PORT: 3000
